version: "3"
services:
    db:
        container_name: mydb
        image: mysql:latest
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
         build:
           context: .
         container_name: app
         ports:
            - "5000:5000"
         volumes:
            - .:/app
         links:
            - "db"
         environment:
            - HOST="YOUR_HOST"
            - PORT="YOUR_PORT"
            - username="YOUR_USERNAME"
            - databast_name="YOUR_DATABASE_NAME"